# Site settings
title: AustinTechVideos.com
email: austintechvideos@llbbl.com
description: "Nerdin it up in Austin"
baseurl: ""
url: "http://www.austintechvideos.com/"

# Build settings
markdown: kramdown
permalink: pretty
