# Site settings
title: AustinTechVideos.com
email: austintechvideos@llbbl.com
description: "Nerdin it up in Austin"
baseurl: "http://llbbl.github.io/static.austintechvideos.com/"
url: "http://www.austintechvideos.com/"

# Build settings
markdown: kramdown
permalink: pretty
