# Site settings
title: AustinTechVideos.com
email: austintechvideos@llbbl.com
description: "Nerdin it up in Austin"
baseurl: ""
url: ""


# Build settings
markdown: kramdown
permalink: pretty
exclude: node_modules, bower_components