# Site settings
title: AustinTechVideos.com
email: austintechvideos@llbbl.com
description: "Nerdin it up in Austin"
baseurl: "http://www.austintechvideos.com/"
url: ""

# Build settings
markdown: kramdown
permalink: pretty
